const $ = (id) => document.getElementById(id);
const DEFAULT_API = 'https://northstar-runner.tail57c12c.ts.net';
const config = () => ({url: localStorage.getItem('northstar.apiUrl') || DEFAULT_API});
let reportIndex=[];
async function get(path){const c=config();const r=await fetch(c.url.replace(/\/$/,'')+path,{cache:'no-store'});if(!r.ok)throw Error(`Northstar API returned ${r.status}.`);return r.json()}
function showError(e){$('message').textContent=e.message;$('report').hidden=true;$('report-html').hidden=true}
function escapeHtml(value){return String(value).replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function inlineMarkdown(value){return escapeHtml(value).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>')}
function markdownToHtml(markdown){const lines=String(markdown||'').split(/\r?\n/),out=[];let inCode=false,code=[];for(const line of lines){if(line.trim().startsWith('```')){if(inCode){out.push(`<pre class="code-block"><code>${escapeHtml(code.join('\n'))}</code></pre>`);code=[];inCode=false}else inCode=true;continue}if(inCode){code.push(line);continue}if(!line.trim()){continue}if(/^#{1,6}\s/.test(line)){const m=line.match(/^(#{1,6})\s+(.*)$/);out.push(`<h${m[1].length}>${inlineMarkdown(m[2])}</h${m[1].length}>`);continue}if(/^[-*]\s+/.test(line)){if(!out.length||!out[out.length-1].startsWith('<ul>'))out.push('<ul>');out[out.length-1]=out[out.length-1].replace('</ul>','')+`<li>${inlineMarkdown(line.replace(/^[-*]\s+/,''))}</li></ul>`;continue}if(/^\d+\.\s+/.test(line)){if(!out.length||!out[out.length-1].startsWith('<ol>'))out.push('<ol>');out[out.length-1]=out[out.length-1].replace('</ol>','')+`<li>${inlineMarkdown(line.replace(/^\d+\.\s+/,''))}</li></ol>`;continue}if(/^---+$/.test(line.trim())){out.push('<hr>');continue}out.push(`<p>${inlineMarkdown(line)}</p>`)}if(inCode)out.push(`<pre class="code-block"><code>${escapeHtml(code.join('\n'))}</code></pre>`);return out.join('')}
function populateReports(reports){reportIndex=reports||[];const select=$('report-select');select.replaceChildren();if(!reportIndex.length){select.add(new Option('No reports available',''));select.disabled=true;return}reportIndex.forEach((r,i)=>select.add(new Option(r.filename||r.id,r.id)));select.disabled=false;select.value=reportIndex[0].id}
async function loadReport(id){if(!id)return;const detail=await get('/api/v1/reports/'+encodeURIComponent(id));$('report').textContent=detail.markdown||'';$('report-html').innerHTML=markdownToHtml(detail.markdown||'');$('report-html').hidden=false;$('report').hidden=true;$('raw-toggle').disabled=false;$('raw-toggle').textContent='View raw Markdown';$('message').textContent=id===reportIndex[0]?.id?'Latest executive report':'Archived executive report';$('report-badge').textContent=id===reportIndex[0]?.id?'Current':'Archived';$('report-time').textContent=reportIndex.find(r=>r.id===id)?.filename||id}
const DISPLAY_NAMES={'Blue-Ridge-Server-2025':'BR-WINDOWS-11','BLUE-RIDGE-SERV':'BR-WINDOWS-11'};
const HOST_DEVICES=new Set(['Blue-Ridge-Server-2025','BLUE-RIDGE-SERV']);
function isServer(device){const raw=device.hostname||device.dns_name||'';if(HOST_DEVICES.has(raw))return false;const name=raw.toLowerCase();return /(server|nexus|exit|warp|host|pi|staging)/.test(name)}
function displayName(device){const name=device.hostname||device.dns_name||'Unnamed device';return DISPLAY_NAMES[name]||name}
function renderGroup(id, devices){const list=$(id);list.replaceChildren();if(!devices.length){const li=document.createElement('li');li.className='empty';li.textContent='None reported';list.append(li);return}devices.sort((a,b)=>(a.hostname||'').localeCompare(b.hostname||'')).forEach(device=>{const li=document.createElement('li');const network=device.network==='cloudflare-warp'?'Cloudflare WARP mesh':'';li.innerHTML=`<span class="device-dot ${device.online?'good':'bad'}"></span><span><strong>${escapeHtml(displayName(device))}</strong><small>${network||device.os||'Unknown OS'}${!network&&device.tailscale_ips?.[0]?' • '+device.tailscale_ips[0]:''}</small></span>`;list.append(li)})}
function renderFleet(status){const rawPeers=status.peers||[];const names=new Set(rawPeers.map(device=>(device.hostname||device.dns_name||'').replace(/\.tail.*$/,'')));const peers=rawPeers.filter(device=>{const name=(device.hostname||device.dns_name||'').replace(/\.tail.*$/,'');return !(name.endsWith('-podman')&&names.has(name.slice(0,-7)))});const groups={serversOnline:[],serversOffline:[],hostsOnline:[],hostsOffline:[]};peers.forEach(device=>{const key=isServer(device)?(device.online?'serversOnline':'serversOffline'):(device.online?'hostsOnline':'hostsOffline');groups[key].push(device)});Object.entries(groups).forEach(([key,devices])=>{renderGroup(key.replace(/([A-Z])/g,'-$1').toLowerCase(),devices);$(`${key.replace(/([A-Z])/g,'-$1').toLowerCase()}-count`).textContent=devices.length});$('servers-total').textContent=groups.serversOnline.length+groups.serversOffline.length;$('hosts-total').textContent=groups.hostsOnline.length+groups.hostsOffline.length}
async function refresh(){try{$('message').textContent='Refreshing…';$('report-badge').textContent='Loading';const [s,r]=await Promise.all([get('/api/v1/status'),get('/api/v1/reports')]);let latestDetail=null;if(r.reports?.[0])latestDetail=await get('/api/v1/reports/'+encodeURIComponent(r.reports[0].id));$('runner').textContent=s.backend_state||'Unknown';$('runner-detail').textContent=`${s.control_plane?.online_count??'—'} devices online in the control plane`;$('runner-dot').className=s.backend_state==='Running'?'good':'bad';const cp=s.control_plane||{};$('device-count').textContent=cp.device_count??'—';$('online').textContent=cp.online_count??'—';renderFleet(s);populateReports(r.reports||[]);if(latestDetail){$('report').textContent=latestDetail.markdown||'';$('report-html').innerHTML=markdownToHtml(latestDetail.markdown||'');$('report-html').hidden=false;$('report').hidden=true;$('raw-toggle').disabled=false;$('raw-toggle').textContent='View raw Markdown';$('message').textContent='Latest executive report';$('report-badge').textContent='Current';$('report-time').textContent=r.reports[0].filename}else{$('message').textContent='No report is available yet.';$('report-badge').textContent='Unavailable'}}catch(e){$('runner').textContent='Unavailable';$('runner-dot').className='bad';$('report-badge').textContent='Offline';showError(e)}}
function openSettings(){const c=config();$('api-url').value=c.url;$('settings-dialog').showModal()}
$('settings').onclick=openSettings;$('refresh').onclick=refresh;$('save').onclick=(event)=>{event.preventDefault();localStorage.setItem('northstar.apiUrl',$('api-url').value.trim()||DEFAULT_API);$('settings-dialog').close();refresh()};
 $('report-select').onchange=()=>loadReport($('report-select').value).catch(showError);$('raw-toggle').onclick=()=>{const raw=$('report').hidden;$('report').hidden=!raw;$('report-html').hidden=raw;$('raw-toggle').textContent=raw?'View formatted report':'View raw Markdown'};
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');if(config().url)refresh();
